### ISSUE TITLE
CSS highlighting doesn't work with just `lang="postcss"`

### ISSUE THREAD

**Issue by babichjacob** [svelte-add/postcss#12]
I came here to post an issue which might be related -- CSS highlighting doesn't work with just `lang="postcss"`
![image](https://user-images.githubusercontent.com/18269460/111080220-d3b8c680-84d3-11eb-9b4f-1ec4fd92f0f8.png)

But it does work if you add the style attribute as well:
![image](https://user-images.githubusercontent.com/18269460/111080244-f77c0c80-84d3-11eb-9778-88bbd9968d12.png)

Despite it being specified as a default in `svelte.config.cjs`:
```
preprocess: [
		sveltePreprocess({
			defaults: {
				style: "postcss",
			},
			postcss: true
		}),
		]
```

_Originally posted by @droher in https://github.com/svelte-add/tailwindcss/issues/12#issuecomment-798958459_

**Comment by dummdidumm** [comment]
Syntax highlighting for PostCSS is turned off in the Svelte for VS Code extension because there are so many PostCSS flavors and we didn't have the capacity to add syntax highlighting for that as well. If there is some kind of "works for 80%" syntax highlighting that is easily integrateable, let me know. I'm also curious why the additional style tag would work in this case.

**Comment by babichjacob** [comment]
> Syntax highlighting for PostCSS is turned off in the Svelte for VS Code extension because there are so many PostCSS flavors and we didn't have the capacity to add syntax highlighting for that as well. If there is some kind of "works for 80%" syntax highlighting that is easily integrateable, let me know. I'm also curious why the additional style tag would work in this case and bring back highlighting.


I don't know. This just restores regular CSS highlighting.

**Comment by dummdidumm** [comment]
Mhm might be the regex that then thinks "oh this is css" again

**Comment by babichjacob** [comment]
Closed by https://github.com/sveltejs/language-tools/issues/996#issuecomment-853780072
