### ISSUE TITLE
Inserting extra "style" into <style> tag.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/postcss#15]
I think there is an extra "style" being added here:
https://github.com/svelte-add/postcss/blob/c07100c57b1f6a75252e57fbaad305f9079825a1/preset.ts#L147

**Comment by babichjacob** [comment]
This is deliberate to enable regular CSS highlighting in `style` blocks. Removing it would make the blocks uncolored, but you can do that in your own projects if you'd like. See #12.
