### ISSUE TITLE
`matchSveltePreprocess` does not match multi-line options.

### ISSUE THREAD

**Issue by Leftium** [svelte-add/postcss#16]
`matchSveltePreprocess` fails to match the following `sveltePreprocess()`:

    preprocess: sveltePreprocess({
        coffeescript: { bare: true }
    }),

This is because [`.*` does not capture newlines](https://stackoverflow.com/a/1981692/117030) in JS regex: https://regex101.com/r/euEPTB/1

`/sveltePreprocess\(([^)]*)\)/m` works: https://regex101.com/r/tdDHd9/1

Even though this works, regex is quite fragile: if the options contain `)` the regex would not capture the full options.

**Relevant code:** https://github.com/svelte-add/postcss/blob/c07100c57b1f6a75252e57fbaad305f9079825a1/preset.ts#L128

**Comment by babichjacob** [comment]
The default `npm init svelte@next` process will create no such function call.

**Comment by Leftium** [comment]
Well, I'm trying to write a coffeescript adder that will modify svelte.config.cjs like that. What if I want to use both:

    npm init svelte@next
    npx svelte-add postcss
    npx svelte-add coffee

Assuming sveltePreprocess() doesn't have any (multiline) options breaks the composability of the adders.

**Comment by babichjacob** [comment]
> 
> 
> Well, I'm trying to write a coffeescript adder that will modify svelte.config.cjs like that. What if I want to use both:
> 
> ```
> npm init svelte@next
> npx svelte-add postcss
> npx svelte-add coffee
> ```
> 
> Assuming sveltePreprocess() doesn't have any (multiline) options breaks the composability of the adders.

Great point! Working on a fix within the hour.
