### ISSUE TITLE
npm run dev shows unstyed page

### ISSUE THREAD

**Issue by NoelJacob** [svelte-add/postcss#6]
```
npm init svelte@next # No TS, CSS only
npx use-preset babichjacob/svelte-add-postcss --no-ssh  # Update node dependencies = No
npx use-preset babichjacob/svelte-add-tailwindcss --no-ssh # Update node dependencies = No
npm install
npm run dev -- --open
```
After that I just get an [unstyled](https://imgur.com/a/Kk3CnqK) webpage

**Comment by babichjacob** [comment]
I'm sorry to say following your exact commands / instructions worked for me.

OS: macOS 11.1
Node: 14.15.2
npm: 6.14.9

**Comment by NoelJacob** [comment]
My device has-

OS: Windows 10 version: 1909
Node: 14.15.3
npm: 6.14.9

Earlier, I had used the postcss+tailwind template which ran fine. I don't know which version but it had "resolutions":{"snowpack":"2.17.0"} in package.json.

**Comment by NoelJacob** [comment]
Converting CRLF line endings to LF after running both the `npx use-preset` solves the problem. 

After `npx use-preset babichjacob/svelte-add-postcss --no-ssh` the following files are converted from CRLF to LF :
```
postcss.config.js
src\routes\$layout.svelte
src\routes\global.pcss
```
and after `npx use-preset babichjacob/svelte-add-tailwindcss --no-ssh` , `tailwind.config.js` is converted and everything runs smoothly.

I installed [Swiss File Knife ](http://stahlworks.com/dev/index.php?tool=remcrlf)(scoop) after that did `sfk remcr -dir . -yes` in the directory to convert line endings.

**Comment by babichjacob** [comment]
> Converting CRLF line endings to LF after running both the `npx use-preset` solves the problem.
> 
> I installed [Swiss File Knife ](http://stahlworks.com/dev/index.php?tool=remcrlf)(scoop) after that did `sfk remcr -dir . -yes` in the directory to convert line endings.
> 
> Edit: changing `core.autocrlf` in git config to `false` takes care of everything.

Is there anything I can modify about the preset(s) to help? (It's not clear)

**Comment by NoelJacob** [comment]
Nope, the fault was at my end. I should have changed git settings to not automatically convert LF line endings to CRLF.
